### PR TITLE
EE-1193: Update wasmi to 0.7

### PR DESCRIPTION
**Pull request by mpapierski**
Ref: https://casperlabs.atlassian.net/browse/EE-1193

- Updates wasmi to 0.7
- pwasm-utils to 0.16
- Fixes transfer benchmark
- Fixes typos in code that were present in wasmi 0.6 and which were also propagated to our code (comparision vs comparsion)
- Explicit default wasm module of a gas function

Benchmark results against dev (with 67d8b2370cc4d62d5b8cc619a4f750fbcfc1c69c commit cherry picked)

https://gist.github.com/mpapierski/65a9949fdd8da4ea20e16d678e5fd769

### CODE REVIEW

**Review by henrytill — APPROVED** [review]
Excellent

**Comment by goral09** [comment]
As far as I can see, there are no performance degradation nor improvements. Do we know what has changed and whether we can make use of that?

**Comment by mpapierski** [comment]
> 
> 
> As far as I can see, there are no performance degradation nor improvements. Do we know what has changed and whether we can make use of that?

I haven't inspected changes manually but the performance report gives me impression not much changed in the interpreter. I think all the relevant changes in wasmi are already reflected in this PR.

**Pull request merged**
