### PR TITLE
NDRS-543: add ability to convert simple CLValues to JSON

### PR DESCRIPTION
**Pull request by Fraser999**
The simplest way (based on recent experience of trying different approaches) is to implement/derive `Serialize` and `Deserialize` and special case for human-readable where required.

This has rippled through to several EE types.

The types for which CLValue has a JSON representation are the simple types, `Option` of simple types, `Result<T, i32>`, `Result<T, u32>`, `Result<T, ()>` and `Result<T, String>` where `T` are the simple types.  I believe these provide a balance between being  immediately useful types for contract authors, and not requiring too large a code explosion in `CLValue`.

### CODE REVIEW

**Review by dwerner — APPROVED** [review]

**Review by henrytill — APPROVED** [review]

**Comment by goral09** [comment]
Does it change how the clients interact with the contracts? I.e. does it change how arguments to contracts are encoded on the client? Or does it only change the display part when clients query the state?

**Comment by Fraser999** [comment]
This one is only about how the values are displayed to the user after the client queries the state.  It does somewhat open the door to being able to have users pass `CLValue`s in via JSON too, but that's out of scope for this ticket and I'm not convinced it's even desirable.

**Comment by goral09** [comment]
Thanks.

**Pull request merged**
