### PR TITLE
NDRS-1028: Optimize handling of finality signatures in the linear chain component.

### PR DESCRIPTION
**Pull request by goral09**
This PR makes a couple of changes that optimize how finality signatures are being handled by the node:
* we gossip finality signatures created only by our node
* we validate the cryptographic signature at the end (as it's the most expensive test)
* validator reactor will inform `LinearChain` when a already-exected block is finalized, so that `LinearChain` can update its view about the tip of the chain and handle `IsBonded` queries properly.

### CODE REVIEW

**Comment by goral09** [comment]
@afck you have already reviewed all but last commit.

**Review by afck — APPROVED** [review]
No blockers from my side. (But Clippy is always right, of course.)

**Comment by goral09** [comment]
bors merge

**Comment by goral09** [comment]
bors cancel

**Pull request merged**
