### PR TITLE
NO TICKET: joiner-dev-tmux.sh now shares assets with run-dev-tmux.sh

### PR DESCRIPTION
**Pull request by xcthulhu**

### CODE REVIEW

**Comment by xcthulhu** [comment]
A recent change to the `config.toml` format that @afck made wasn't propagated to my joiner tests, so I've changed the joiner tests to just have symbolic links to the other local test config used in the test scripts.

**Review by afck — COMMENTED** [review]
Why not delete the whole `resources/joiner` directory then, and just use `resources/local`?

**Comment by xcthulhu** [comment]
> Why not delete the whole resources/joiner directory then, and just use resources/local?

I need a custom [accounts.csv][1] with just one bonded validator.

[1]: https://github.com/CasperLabs/casper-node/blob/630a446002ea574bf011168c944cca94de0bf2d2/resources/joiner/accounts.csv

**Review by afck — APPROVED** [review]

**Comment by xcthulhu** [comment]
bors +r

**Comment by xcthulhu** [comment]
bors merge

**Pull request merged**
