### PR TITLE
NO-TICK: offset timestamp in run-dev.sh by 30 seconds

### PR DESCRIPTION
**Pull request by arcolife**
```
╰─ OFFSET=50 ./run-dev.sh
GENESIS_TIMESTAMP=1600862573000
Wed Sep 23 17:32:53 IST 2020
...
```

@afck Default's to 30. Ref https://github.com/CasperLabs/casper-node/pull/260

### CODE REVIEW

**Comment by afck** [comment]
I can't try it locally; somehow the script doesn't seem to start the nodes anymore, even on `master`.

**Comment by goral09** [comment]
> I can't try it locally; somehow the script doesn't seem to start the nodes anymore, even on `master`.

That's my fault. `./run-dev.sh` won't try all nodes anymore (I have a fix on my branch). You need to tell it explicitly which nodes to start: `./run-dev.sh 1 2 3 4 5`

**Comment by afck** [comment]
Sorry, I should have remembered that! :man_facepalming: 
But now I run into the other issue where the script for mysterious reasons compiles the node _agan_ — which counts towards our 30 seconds… :grimacing:

**Review by afck — APPROVED** [review]
Approving, since I'm pretty sure the issues I'm seeing are unrelated to this PR.

It did start for me now, but failed to progress to era 1. It looks like not all nodes managed to connect to each other, which may be related to the cargo build problem — that causes them all to start at exactly the same time.

**Comment by goral09** [comment]
> But now I run into the other issue where the script for mysterious reasons compiles the node agan — which exceeds our 30 seconds… 

For me, building with `cargo build -p casper-node` worked and builds it only once.

**Comment by afck** [comment]
> cargo build -p casper-node

But that's exactly what the script is already trying to do in advance.
I even tried running it manually before `run-dev.sh`, but that didn't change anything.

**Review by goral09 — APPROVED** [review]

**Comment by arcolife** [comment]
btw @afck it worked with `OFFSET=90` for me. Indet issues again?

**Comment by afck** [comment]
With `OFFSET=90` all nodes started for me, but only some seemed to produce blocks and votes, and none of them arrived in era 1. (I found the string "`era_id: 0`" in some logs, but none contained "`era_id: 1`", not even after a few minutes.)

**Comment by arcolife** [comment]
@afck so non-det issue for sure, coz I went upto Era 20 before I stopped!

**Comment by afck** [comment]
Ah, great!
I tried twice and neither made it to era 1, but maybe that's something specific to my setup somehow.

**Pull request merged**
