### PR TITLE
EE-1057: Fix withdraw bid for validators

### PR DESCRIPTION
**Pull request by mpapierski**
Ref: https://casperlabs.atlassian.net/browse/EE-1057

Discovered while working on https://casperlabs.atlassian.net/browse/EE-1045 (#311) - fixes `withdraw_bid` for genesis validators

- Adds the genesis purse into `bid_purses`, so the genesis bid can be found while withdrawing unlocked funds
- Fixes off by one error where the result of computation was not preserved in the collection.

### CODE REVIEW

**Review by henrytill — APPROVED** [review]
:+1:

**Review by EdHastingsCasperLabs — APPROVED** [review]
nit: I'd prefer if you included assert messages that communicate what a failure represents, but not blocking over it.

**Pull request merged**
