### PR TITLE
HWY-242: Fix DataSize implementation for HighwayProtocol

### PR DESCRIPTION
**Pull request by afck**
`estimate_heap_size` was called on `&HighwayProtocol` instead of `HighwayProtocol` and returned `0`.

https://casperlabs.atlassian.net/browse/HWY-242

### CODE REVIEW

**Review by marc-casperlabs — APPROVED** [review]
It does look good to me, I would suggest we fix the remaining `impl`s in a separate PR once `datasize` has caught up. The `BTreeSet` one looks important at least.

**Comment by afck** [comment]
It only matters if there are equivocations and endorsements, so at least we'll get useful data from our tests with this PR. But I'll work on the `BTreeSet` impl, too.

**Review by goral09 — APPROVED** [review]

**Comment by afck** [comment]
https://github.com/CasperLabs/datasize-rs/pull/5 adds support for `BTreeSet`. (And I was wrong: It's already implemented for `PathBuf`.)

**Pull request merged**
