### PR TITLE
EE-1223: Remove get refund purse

### PR DESCRIPTION
**Pull request by mpapierski**
Ref: https://casperlabs.atlassian.net/browse/EE-1223

Removes `get_refund_purse` entry point altogether as we were returning an `URef` there without access rights which could pose a security risk.

### CODE REVIEW

**Review by darthsiroftardis — APPROVED** [review]
LGTM! I would wait for another greencheck

**Comment by goral09** [comment]
What security risks? A purse without access rights can't be used for taking the money out of it. Even the comment says:
```
// We purposely choose to remove the access rights so that we do not
// accidentally give rights for a purse to some contract that is not
// supposed to have it.
```

**Review by henrytill — APPROVED** [review]
Merge away!

**Comment by mpapierski** [comment]
> 
> 
> What security risks? A purse without access rights can't be used for taking the money out of it. Even the comment says:
> 
> ```
> // We purposely choose to remove the access rights so that we do not
> // accidentally give rights for a purse to some contract that is not
> // supposed to have it.
> ```

Correct - if there are no access rights, then there's no reason to expose this URef at all to contract developer

**Comment by goral09** [comment]
> > What security risks? A purse without access rights can't be used for taking the money out of it. Even the comment says:
> > ```
> > // We purposely choose to remove the access rights so that we do not
> > // accidentally give rights for a purse to some contract that is not
> > // supposed to have it.
> > ```
> 
> Correct - if there are no access rights, then there's no reason to expose this URef at all to contract developer

Thanks. It can still be used in some in-smart-contract manipulation like equality check. It can be transferred to other smart contracts (also without access rights). It's just not useful when trying to read/write/add to it but still pretty useful to me.

**Pull request merged**
