### PR TITLE
NO-TICKET: Log the era supervisor's public key

### PR DESCRIPTION
**Pull request by xcthulhu**

### CODE REVIEW

**Comment by xcthulhu** [comment]
I found this helpful in debugging logs for the local network runners.

**Review by afck — COMMENTED** [review]
We could add it to [this](https://github.com/CasperLabs/casper-node/blob/7efb351a0384b7d6d8e2b1ac556fc22ee1e7fffc/node/src/components/consensus/era_supervisor.rs#L263) and maybe [this](https://github.com/CasperLabs/casper-node/blob/7efb351a0384b7d6d8e2b1ac556fc22ee1e7fffc/node/src/components/consensus/era_supervisor.rs#L260) log message instead, when activating as a validator. (Because for read-only nodes — which never activate — the public signing key is not relevant.)

It would also be good to have a consistent terminology: It's called `our_id` in [other log messages](https://github.com/CasperLabs/casper-node/blob/7efb351a0384b7d6d8e2b1ac556fc22ee1e7fffc/node/src/components/consensus/era_supervisor.rs#L257).

**Review by Fraser999 — APPROVED** [review]

**Review by afck — APPROVED** [review]

**Comment by xcthulhu** [comment]
> We could add it to [this](https://github.com/CasperLabs/casper-node/blob/7efb351a0384b7d6d8e2b1ac556fc22ee1e7fffc/node/src/components/consensus/era_supervisor.rs#L263) and maybe [this](https://github.com/CasperLabs/casper-node/blob/7efb351a0384b7d6d8e2b1ac556fc22ee1e7fffc/node/src/components/consensus/era_supervisor.rs#L260) log message instead, when activating as a validator. (Because for read-only nodes — which never activate — the public signing key is not relevant.)
> 
> It would also be good to have a consistent terminology: It's called `our_id` in [other log messages](https://github.com/CasperLabs/casper-node/blob/7efb351a0384b7d6d8e2b1ac556fc22ee1e7fffc/node/src/components/consensus/era_supervisor.rs#L257).

I went ahead and made these changes in https://github.com/CasperLabs/casper-node/pull/798/commits/82574cf2135bd83cba544d9ee739224a29e0c81d and https://github.com/CasperLabs/casper-node/pull/798/commits/252c09c0c76450d7fbac69feab3c0112d576aa14

**Comment by xcthulhu** [comment]
bors merge

**Pull request merged**
