### PR TITLE
NDRS-471: [deploy-buffer] prune dependencies

### PR DESCRIPTION
**Pull request by dwerner**
I put together an implementation that traverses to the first level of dependencies - this could be much nicer but tried to make things efficient by chaining iterators where I could. If there's a clearer way to do this I'm very much open to suggestions.

This is branched from #295 so only the last few commits (since requesting review) are relevant.

### CODE REVIEW

**Comment by goral09** [comment]
Commit history on this is bit messy :grimacing: I like reviewing PRs commit-by-commit whenever it's possible (meaning granular commits with good message). Can you try it next time? It will make reviewers' life and job easier.

**Review by afck — COMMENTED** [review]
I'd have attempted to recursively remove all deploys depending directly and indirectly on an expired one — but I guess that could potentially waste a lot of CPU time, if there are long chains of dependencies? Also, it wouldn't work across different pruning steps, unless we had another collection of all _expired_ deploys, which would waste memory again. So I guess that's better left for later, and maybe solved with a bloom filter after all.

Apart from that, I find the amount of local functions inside `prune` a bit confusing. I wonder whether they should be moved to a `pruning` submodule; or become methods of `ProtoBlockCollection` and `DeployCollection`, either via an extension trait, or by making those types actual wrappers instead of just aliases. Nor sure what's best.

**Comment by goral09** [comment]
BTW I am waiting with the review once https://github.com/CasperLabs/casper-node/pull/295 is merged.

**Comment by dwerner** [comment]
Closing this PR, changes are now here: https://github.com/CasperLabs/casper-node/pull/330

**Pull request closed without merging**
