### PR TITLE
OP-1838 + OP-1839: shutdown validator during native/wasm transfer testing scenarios

### PR DESCRIPTION
**Pull request by linclelinkpart5**
Still working on splitting out common functionality and reusing existing logic from other scenarios, but wanted to get feedback earlier rather than later.

### CODE REVIEW

**Comment by TomVasile** [comment]
overall it looks right so far ,but seems to miss part of these scenarios which was to track what happens to deploys that were in the nodes buffer.

**Comment by TomVasile** [comment]
I pulled the PR and gave it a run. I noticed the drain seemed to go extremely quick, so I threw a couple `log "num_pending: $NUM_PENDING"` statements around and it doesn't seem to return.

```
2021-03-03T03:45:26.226742 [INFO] [21466] NCTL :: STEP 7: waiting for pendings deploys to drain
2021-03-03T03:45:26.243845 [INFO] [21466] NCTL :: endpoint: http://localhost:50102/metrics
2021-03-03T03:45:26.245494 [INFO] [21466] NCTL :: num_pending:
2021-03-03T03:45:26.247000 [INFO] [21466] NCTL :: num_pending:
2021-03-03T03:45:26.248709 [INFO] [21466] NCTL :: ------------------------------------------------------------
2021-03-03T03:45:26.250294 [INFO] [21466] NCTL :: STEP 8: awaiting full synchronization of node=2…
```

I also noticed that the `no_hup.out` is still spitting out.

```
$ ls utils/nctl/sh/scenarios/
itst01.sh  itst02.sh  itst06.sh  itst07.sh  itst11.sh  nohup.out  sync_test.sh  sync_upgrade_test.sh
```

**Comment by linclelinkpart5** [comment]
Weird, I'm observing the nohup.out being generated on my end now too. I'll fix that and see what the deal is with the `$NUM_PENDING` as well.

**Comment by TomVasile** [comment]
@linclelinkpart5 can you merge dev and refactor to use `utils/nctl/sh/scenarios/common/itst.sh` should de-dup a bunch of lines.

**Comment by TomVasile** [comment]
@linclelinkpart5 Re-pulled the pr and gave it a run. Same issue.

added: `log "DEBUG: num_pending::while:: num_pending=$NUM_PENDING endpoint=$ENDPOINT"` to your `num_pending` function's while loop.

`$NUM_PENDING` is always empty.


```
2021-03-05T18:50:26.865353 [INFO] [11326] NCTL :: STEP 7: waiting for pending deploys to drain
2021-03-05T18:50:27.883423 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:28.903206 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:29.919414 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:30.935576 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:31.951816 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:32.967859 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:33.983632 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:35.000014 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
2021-03-05T18:50:36.018031 [INFO] [11326] NCTL :: DEBUG: num_pending::while:: num_pending= endpoint=http://localhost:50101/metrics
...
...
```

**Comment by TomVasile** [comment]
@linclelinkpart5 I think this still needs another check to be complete. It's currently only checking that the deploys are draining but not verifying that deploys that were sent actually get finalized eventually.

**Comment by linclelinkpart5** [comment]
@TomVasile That's a good point, let me figure out how to verify that, and I'll add in that functionality.

**Comment by TomVasile** [comment]
pulled locally, closing for now.

**Pull request closed without merging**
