### PR TITLE
NDRS-399: Fix metrics

### PR DESCRIPTION
**Pull request by marc-casperlabs**
Every reactor runner used to come with its own metrics registry, which mean that metrics were not reported properly when going from one reactor to the next.

This PR changes the interface of the runner, making it possible to share a preconstructed registry for metrics that is shared across initializer, joiner and validator.

This requires properly deregistering metrics when dropping a runner/shared component, which is done only for the runner. Should someone attempt to drop and recreate a contract runtime at some point, this will need to be added to the contract runtime metrics as well. For now this is not an issue though and it will be apparent quickly during development, as it will cause a panic when creating the follow-up reactor.

### CODE REVIEW

**Review by EdHastingsCasperLabs — APPROVED** [review]

**Comment by goral09** [comment]
What was the problem with metrics? Description isn't clear on that. Didn't `validator` reactor correctly instantiate its Metrics registry?

**Comment by marc-casperlabs** [comment]
> What was the problem with metrics? Description isn't clear on that. Didn't validator reactor correctly instantiate its Metrics registry?

Creating a new reactor would also create a new registry for metrics; each reactor would have its own instance. Any component that was not recreated but passed from the previous reactor to the next would retain its link to the old metrics instance. In short, metrics for the contract runtime were dutifully increased on a registry that was never again asked to provide these metrics, which a new one that had almost no component registered on it would be tasked to answer client responses.

**Comment by marc-casperlabs** [comment]
> Thanks for the explanation. I would have thought that old metric registry would be dropped when we transition from joiner to validator reactor and Rust compiler wouldn't even allow for the new components to have reference to the old metric registry?

Unfortunately, the way the `prometheus` crate is designed, a `Registry` in reality is an `Arc` in disguise, so it will happily keep on going in the background. =(

**Pull request merged**
