### PR TITLE
1. Added 'net=' to invocation of 'node/status.sh' in 'node/stop.sh' 2. Added new chainspec.toml fields to nctl's copy

### PR DESCRIPTION
**Pull request by linclelinkpart5**
Adding `net=` to the call to `status.sh` in `stop.sh`, `$net` gets clobbered with the default value of 1 otherwise.

### CODE REVIEW

**Review by momipsl — APPROVED** [review]
Fine attention to detail !

**Comment by linclelinkpart5** [comment]
@momipsl Seems bors and drone aren't happy with my changes, would you have some time tomorrow to help me work these out Mark? I really appreciate it!

**Comment by goral09** [comment]
@linclelinkpart5 It looks like it's my fault. A non-det failure haunted your PR. I will create a PR with a fix.

**Comment by goral09** [comment]
bors try

**Comment by linclelinkpart5** [comment]
@goral09 Thank you! I'll refresh from master and try this again.

**Comment by linclelinkpart5** [comment]
bors try

**Pull request merged**
