### PR TITLE
NDRS-504: replace rmp_serde with bincode

### PR DESCRIPTION
**Pull request by Fraser999**
We recently discovered that the rmp_serde encoder and decoder currently reports its type as human readable.  Since recent changes to our code specialise (de)serialisation for human-readable formats (generally by encoding byte strings to hex, hence doubling their size), we need to change to an encoding format which is not classed as human-readable.

Note, this PR is based off https://github.com/CasperLabs/casper-node/pull/347, so only the final commit should be reviewed here.

### CODE REVIEW

**Review by dwerner — APPROVED** [review]

**Review by henrytill — APPROVED** [review]

**Review by EdHastingsCasperLabs — APPROVED** [review]
Boss move w/ ExecutableDeployItem; lgtm

**Pull request merged**
