### PR TITLE
NO-TICKET: fix issue in gossip table

### PR DESCRIPTION
**Pull request by Fraser999**
Ported #1021 to `master`.

### CODE REVIEW

**Comment by goral09** [comment]
I you had used `git cherry-pick <original hash>` then it would have been easier to review it.

**Comment by Fraser999** [comment]
I cherry-picked the commit from https://github.com/CasperLabs/casper-node/pull/1022.  The only difference between the original commit and these two is the addition of the comments to the tests you requested.

**Comment by goral09** [comment]
> I cherry-picked the commit from #1022. The only difference between the original commit and these two is the addition of the comments to the tests you requested.

Oh, sorry then. I thought that cherry-pick'd commits have a different structure and link to the original one. My bad.

**Review by goral09 — APPROVED** [review]

**Comment by Fraser999** [comment]
bors merge

**Pull request merged**
