### PR TITLE
NDRS-687: Delay era deactivation.

### PR DESCRIPTION
**Pull request by afck**
Since summits are not monotonous, it can happen that we see a switch block finalized but other honest validators don't, because they first see an equivocation that invalidates the summit.

To make it more likely that everyone sees the switch block finalized, we keep voting for a while, and only stop once we observed no new equivocations within a period that was sufficient to finalize the block.

https://casperlabs.atlassian.net/browse/NDRS-687

### CODE REVIEW

**Comment by afck** [comment]
I created [NDRS-692](https://casperlabs.atlassian.net/browse/NDRS-692) as a follow-up.

**Review by goral09 — APPROVED** [review]
Looks good. :+1:

I hope there won't be any problems caused by the fact that now we may be actively voting in more than 1 era.

**Comment by afck** [comment]
> I hope there won't be any problems caused by the fact that now we may be actively voting in more than 1 era.

I can't think of any problems. (Famous last words…)

But I'd argue that if there are it's better if we find them now than later! :sweat_smile:

**Comment by afck** [comment]
bors merge

**Pull request merged**
