### PR TITLE
NO-TICKET: Address three TODOs.

### PR DESCRIPTION
**Pull request by afck**
* Remove an obsolete TODO about endorsement evidence size limit. Move the size limit into the `filter` call, with the other conditions.
* Make `Panorama::sees` traverse only the relevant swimlane, if the sender is seen as correct.
* Disconnect from senders of invalid consensus values. Log warnings, not errors, when disconnecting: It doesn't point to a problem with our own node.

### CODE REVIEW

**Review by fizyk20 — APPROVED** [review]
Looks good :+1:

**Review by goral09 — APPROVED** [review]

**Comment by afck** [comment]
bors merge

**Pull request merged**
