### PR TITLE
NDRS-766: introducing joiner-dev-tmux.sh

### PR DESCRIPTION
**Pull request by xcthulhu**

### CODE REVIEW

**Comment by xcthulhu** [comment]
@EdHastingsCasperLabs did some follow-up with @marc-casperlabs so that we can have proper unit tests here, but this is sufficient for now for my purposes.

**Review by EdHastingsCasperLabs — APPROVED** [review]

**Review by henrytill — CHANGES_REQUESTED** [review]
I we should remove the generated joiner `chainspec.toml` and add it to `.gitignore`.

**Comment by goral09** [comment]
You should really try using `nctl`. It's already in this repo, it doesn't add any overhead since it's mostly bash scripts. It already has features like starting the network (`nctl-start`), stopping the network (`nctl-stop`), start/stop single node (`nctl-start|stop node=X`), joining the network using latest available hash (`nctl-join node=6`), joining the network using specific hash (`nctl-start node=6 hash=<hash>`) and much more.

**Review by henrytill — APPROVED** [review]
LGTM

**Pull request merged**
