### PR TITLE
NDRS-842: Have network retry connecting

### PR DESCRIPTION
**Pull request by xcthulhu**
https://casperlabs.atlassian.net/browse/NDRS-842

### CODE REVIEW

**Review by dwerner — COMMENTED** [review]
I'm wondering if we should do some kind of back-off/delay between retries?

**Review by dwerner — APPROVED** [review]

**Review by dwerner — APPROVED** [review]
Cool, looks good to me.

**Comment by xcthulhu** [comment]
Chatted with @dwerner; we should be using `tokio::sync::Mutex` instead of the standard library one.

**Comment by xcthulhu** [comment]
> Chatted with @dwerner; we should be using tokio::sync::Mutex instead of the standard library one.

Okay, so this is tricky to do since we are using this mutex both syncronously and asynchronously now... we'll have to make a follow up ticket for this.

**Comment by xcthulhu** [comment]
bors merge

**Review by EdHastingsCasperLabs — APPROVED** [review]

**Pull request merged**
