### PR TITLE
OP-1928: Mainnet accounts

### PR DESCRIPTION
**Pull request by sacherjj**

### CODE REVIEW

**Review by MParlikar — APPROVED** [review]
SHIP IT.

**Comment by sacherjj** [comment]
bors merge

**Review by ashok-cl — APPROVED** [review]
Go for it Casper!

**Review by Mrinal-Manohar — APPROVED** [review]

**Comment by Mrinal-Manohar** [comment]
Shipped!

**Comment by MParlikar** [comment]
bors merge

**Pull request merged**
