### PR TITLE
Disable `WRITE_MAP` on Mac OS X

### PR DESCRIPTION
**Pull request by marc-casperlabs**
Hotfix to restore performance on Mac OS X (even though not officially supported :))

### CODE REVIEW

**Review by momipsl — APPROVED** [review]
OS_ENVIRONMENT_FLAGS seems a more appropriate name.  But yes this should resolve issue assuming it is indeed MacOSX specific.

**Review by Fraser999 — APPROVED** [review]

**Comment by henrytill** [comment]
I have questions about whether or not it is a good strategy to be introducing platform-specific optimizations like this.  It would seem to me that the safer thing to do would be not use `WRITE_MAP` at all.

cc @EdHastingsCasperLabs

**Comment by henrytill** [comment]
Furthermore, do we have any benchmarks demonstrating an appreciable enough performance gain that it's worth using `WRITE_MAP`?

**Comment by EdHastingsCasperLabs** [comment]
> It would seem to me that the safer thing to do would be not use WRITE_MAP at all.

Agreed. This seems like a premature optimization.

**Comment by henrytill** [comment]
> > It would seem to me that the safer thing to do would be not use WRITE_MAP at all.
> 
> Agreed. This seems like a premature optimization.

And one that asks us to trade some safety guarantees.

**Comment by EdHastingsCasperLabs** [comment]
In the short term, merge this to unbreak mac people. Afterwards I think we should follow up and remove the `WRITE_MAP` behavior altogether.

**Pull request merged**
