### PR TITLE
NDRS-944: Prevent panics on failed connection

### PR DESCRIPTION
**Pull request by marc-casperlabs**
Fixes a very rare race condition where the node did not know how to handle a connection being dropped in the middle of being established. This has, so far, only been triggered once in the recent months, regardless this is a fix for it.

### CODE REVIEW

**Review by Fraser999 — APPROVED** [review]

**Comment by goral09** [comment]
bors merge

**Comment by goral09** [comment]
bors cancel

**Comment by goral09** [comment]
bors merge

**Pull request merged**
