### PR TITLE
Delta 4 Config

### PR DESCRIPTION
**Pull request by sacherjj**
Committing genesis files pushed to S3.
Updated pull_genesis.sh to point to S3 URL.

Funding Faucet, N0, N1, N2, Medha, and bitgo.
Bonding N0, N1, bitgo.  

My expectation is bitgo will move over to the more stable Delta.

### CODE REVIEW

**Review by MParlikar — APPROVED** [review]
LGTM

**Comment by sacherjj** [comment]
bors merge

**Comment by sacherjj** [comment]
bors try

**Pull request merged**
