### PR TITLE
OP-1940: add back removed true

### PR DESCRIPTION
**Pull request by TomVasile**
Adding back a pipe to true that was removed in a recent pr.

### CODE REVIEW

**Comment by TomVasile** [comment]
for reference to the issue: https://github.com/Supervisor/supervisor/issues/1223

**Review by goral09 — APPROVED** [review]

**Comment by TomVasile** [comment]
reference: https://github.com/CasperLabs/casper-node/pull/899/files

**Comment by TomVasile** [comment]
reference: removed here, https://github.com/CasperLabs/casper-node/pull/1220

**Pull request merged**
