### PR TITLE
NDRS-432: Cache chainspec

### PR DESCRIPTION
**Pull request by goral09**
This PR is meant to address read lock exhaustion of the chainspec db observed over heavy loads of incoming deploys. 

The chainspec data includes the deploy config settings such as ttl which is necessary for deploy validation. 

The approach taken by this PR is to lazily initialize an in-memory copy of the chainspec (by protocol version) in the deploy_buffer and deploy_acceptor upon first access to avoid pressuring the chainspec store.

### CODE REVIEW

**Review by EdHastingsCasperLabs — APPROVED** [review]

**Comment by EdHastingsCasperLabs** [comment]
I woke up intending to take a pass at this myself, only to happily discover that @goral09 had ninja'd it. I would like to see this applied to the charlie branch as well and for @momipsl to repeat his test run using it so that we can get some solid comparative data.

**Review by Fraser999 — APPROVED** [review]

**Pull request merged**
