### PR TITLE
NDRS-910: Introducing failing test for joiner with network of multiple nodes

### PR DESCRIPTION
**Pull request by xcthulhu**

### CODE REVIEW

**Comment by goral09** [comment]
Why does this fail @xcthulhu ? We have a very similar test using nctl which does pass.

**Comment by xcthulhu** [comment]
Here's the logs I'm seeing:

```
Feb 17 11:05:38.253 ERROR crank{; node_id=NodeId::Tls(4bd7..cd43)}: [casper_node::effect effect.rs:198] responder(()) dropped without being responded to --- this is always a bug and will likely cause another component to be stuck!
Feb 17 11:05:38.261 ERROR [casper_node::effect effect.rs:406] request for () channel closed, this is a serious bug --- a component will likely be stuck from now on ; err=oneshot canceled; queue_kind=Network
```

I suspect the issue is in the `MultiStageReactor`.  CC @marc-casperlabs

**Comment by goral09** [comment]
If we have already established that this happens when the test transitions from a `joiner` reactor to `validator`, without executing all of the effects, maybe we should add a test-only `reactor::drain()` method that would just process all of the effects without enqueuing their resulting events?

**Review by goral09 — COMMENTED** [review]
The test above that is also called `test_joiner` – can you add a comment what's the difference between them?

**Comment by xcthulhu** [comment]
> The test above that is also called `test_joiner` – can you add a comment what's the difference between them?

Fixed in https://github.com/CasperLabs/casper-node/pull/936/commits/a435a66c8c74ea099af2cb06b1f3dfca893ae097

**Review by goral09 — APPROVED** [review]
And it's still failing b/c of the problems with joiner -> validator reactors transition?

**Comment by xcthulhu** [comment]
> And it's still failing b/c of the problems with joiner -> validator reactors transition?

I think it's because we don't retry connecting...

**Comment by xcthulhu** [comment]
bors merge

**Comment by xcthulhu** [comment]
bors mergge

**Comment by xcthulhu** [comment]
bors merge

**Comment by xcthulhu** [comment]
bors retry

**Comment by xcthulhu** [comment]
bors merge

**Pull request merged**
