### PR TITLE
[Delta] NDRS-963: chainspec loader now gets the protocol version from the highest

### PR DESCRIPTION
**Pull request by goral09**
Ports commit from `release-0.9.1` branch to `release-0.9.2`.

### CODE REVIEW

**Review by Fraser999 — APPROVED** [review]

**Comment by goral09** [comment]
bors merge

**Comment by goral09** [comment]
bors merge

**Comment by goral09** [comment]
bors merge

**Review by EdHastingsCasperLabs — APPROVED** [review]

**Pull request merged**
