### PR TITLE
EE-1168: refactor Mint to remove use of named keys

### PR DESCRIPTION
**Pull request by henrytill**
Ref: https://casperlabs.atlassian.net/browse/EE-1168

This PR
- introduces a `Key::Balance` variant, under which balance values are stored.  These values are only readable and writable by host-side code.
- removes the various URefs used for indirection in the mint code.
- simplifies the structure of balance proofs now that the indirection is gone.

### CODE REVIEW

**Review by dwerner — APPROVED** [review]

**Comment by goral09** [comment]
> introduces a `Key::Balance` variant, under which balance values are stored. These values are only readable and writable by host-side code.

What would have to a dApp developer do to implement something similar to the Mint? Like an ERC20 token that tracks balances of all token holders?

**Comment by dwerner** [comment]
This improves disk use substantially - in a 10 min run spamming with new accounts, we previously reached 1.4gb disk consumption, and with this change it's in the range of 272mb. https://casperlabs.atlassian.net/browse/NDRS-918

**Comment by henrytill** [comment]
> > introduces a `Key::Balance` variant, under which balance values are stored. These values are only readable and writable by host-side code.
> 
> What would have to a dApp developer do to implement something similar to the Mint? Like an ERC20 token that tracks balances of all token holders?

We will need to reintroduce something like `Key::Local` (probably using an arbitrary `URef` as a seed to address versioning concerns).  @EdHastingsCasperLabs and I have been talking about it, but it's lower priority than some of the other optimization work ATM.

**Review by EdHastingsCasperLabs — APPROVED** [review]

**Review by mpapierski — APPROVED** [review]

**Pull request merged**
